source 'https://rubygems.org'

gem 'cpf_utils'

# pode também indicar a versão da gem
# segue abaixo alguns exemplos de notações
# gem 'cpf_utils', '1.3.0' (versão exata para instalar)
# gem 'cpf_utils', '>=1.0.0' (versão maior ou igual para instalar)
# gem 'cpf_utils', '~>1.3.0' (versão parcial até menor que a versão 2.0, vai da 1.3 até menor que 2.0) Versão parcial sem pular a Major, Minor